version: '3.8'

services:
  medicare-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicare-production
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
